substitutions:
  name: temp-garage
  friendly_name: temp garage

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  project:
    name: "esphome.temp-garage"
    version: "1.0.0"

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

dashboard_import:
  package_import_url: github://fjordlax/esphome/temp-garage.yaml@main
  import_full_config: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

dallas:
#  - pin: 2
  pin:
    number: 2
    mode:
      input: true
      pullup: true
sensor:
 - platform: dallas
   address: 0x700008022a0d1210
   name: temperatur-garage


    
