substitutions:
  name: temp-hundkoja
  friendly_name: temp hundkoja

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  project:
    name: "tech dogs"
    version: "1.0.0"

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid2
  password: !secret wifi_password

dallas:
  - pin: 2
sensor:
 - platform: dallas
   address: 0xaa000005459a8028
   name: temperatur hundkoja


    
